### ISSUE TITLE
set prior bug

### ISSUE THREAD

**Issue by wzb-ipi** [integrated-inferences/CausalQueries#273]
there should not be a problem here:
```
> make_model("X -> Y; X <->Y") |> set_priors(node = "X", alphas = c(2,2))
Error in make_par_values(model = model, alter = "priors", x = alphas, :
A specified condition matches multiple parameters. If your model contains confounding your condition applies across multiple param_sets.
In these cases, it is unclear which value should be applied to which parameter. Try specifying the 'param_set' option to clarify which value should
be applied to which parameter.
```

**Comment by till-tietz** [comment]
Thanks for flagging. I know where this issue stems from...overzealous error handling on my part. Will fix today.

**Comment by till-tietz** [comment]
The error message is misleading here. I made make_par_values quite strict in the recent rewrite. What it is complaining about is that just specifying node = "X" matches parameters "X.0" and "X.1" and since the function makes no assumptions about the order of parameters it takes this instruction to be under specified.

**Comment by till-tietz** [comment]
This is behavior is basically the price we're paying for being able to specify alphas not in the order of parameters_df

**Comment by macartan** [comment]
I see; maybe this is too strict. Sorry for back and forths on this.

I'd think node = "X", should basically filter to

model$parameters_df |> filter(node = "X") , which here has two rows and so
either a vector of length 1 or 2 should work

more tricky:

perhaps here we should allow a vector of length 2, but provide a warning
rather than an error?

make_model("X -> Y; X<->Y") |> set_priors(node = "Y", nodal_type = "01",
1:2)

**Comment by till-tietz** [comment]
I think this could actually be an easy fix. There is only one small code section that enforces this strict rule; which we could change into a warning in cases where confounded nodes are implicated in the alter instructions.
