### ISSUE TITLE
help files for s3 methods 

### ISSUE THREAD

**Issue by till-tietz** [integrated-inferences/CausalQueries#323]
not sure if this will do the trick but here is a stackoverflow issue about this 

https://stackoverflow.com/questions/7198758/roxygen2-how-to-properly-document-s3-methods

**Comment by gerasy1987** [comment]
Seems that despite the fact that S3 methods are not exported in package, you can still access the help files for them using `?plot.causal_model` or `?print.causal_model` (the latter works on master branch since I documented that method). So all we need is to write a proper `roxygen2` skeleton for `plot.causal_model`.

@till-tietz @macartan I see that `plot_dag()` has a help file now but it is not intended to be used by users. Do we need to keep `plot_dag()` at all or could it be worth it to move all of that to `plot.causal_model()` and then write a proper skeleton there?

**Comment by gerasy1987** [comment]
@macartan this could be a solution, yes. I'm pretty sure we can add a see also section to the help file and reference the plot method.

**Comment by macartan** [comment]
Great

**Comment by gerasy1987** [comment]
There is a way to force print help information for methods inside help file of "parent" function: we just need to us `@rdname [FUNCTION_NAME]`, e.g.

```r
@rdname summary.causal_model
```

**Comment by till-tietz** [comment]
@gerasy1987 I think your proposal above would be fantastic!!! Let's see if we can figure it out

**Comment by gerasy1987** [comment]
I already implemented the brute force approach with `@rdname` for print and summary methods for `causal_model` class objects produced by `update_update()`. Now the issue here is that those print and summary methods also apply to `make_model()` function, but there is no easy way to include those methods in two help files (see [)](https://roxygen2.r-lib.org/articles/reuse.html)

Given that S3Class does not really support standalone help pages, maybe the way to go is to list all relevant S3 Methods (including plot) in the most base function that produces the `causal_model` class, i.e. `make_model()` and then in `update_model()` just reference the `make_model()` help file? 

For example see `?plot.ecdf()`. Also this could potentially be a solution to the plot issue @macartan mentioned above. I.e. users can always come back to `?make_model()` help file to review `plot.causal_model()` arguments.

**Comment by till-tietz** [comment]
S3s have been implemented + documented up to aligned standard with 1.2.0
