### ISSUE TITLE
summary / print issues

### ISSUE THREAD

**Issue by macartan** [integrated-inferences/CausalQueries#334]
Note numbers change as well as contents; so weird that the summary method gets applied after `head`? Can we avoid this?

> grab(model, object = "posteriors")
Summary statistics of model parameter posterior distributions:
Draws: 4000
rows are parameters
     mean   sd
X.0  0.50 0.29
X.1  0.50 0.29
Y.00 0.25 0.19
Y.10 0.25 0.19
Y.01 0.25 0.19
Y.11 0.25 0.20

> grab(model, object = "posteriors") |> **head()**
Summary statistics of model parameter posterior distributions:
**Draws: 6**
rows are parameters
     mean   sd
X.0  0.60 0.24
X.1  0.40 0.24
Y.00 0.22 0.08
Y.10 0.29 0.15
Y.01 0.19 0.18
Y.11 0.31 0.29
```

**Comment by macartan** [comment]
model$posterior_event_probabilities
needs a method

Currently:

> grab(model, "event_probabilities")
     event_probs
X0Y0        0.25
X1Y0        0.25
X0Y1        0.25
X1Y1        0.25

> grab(model, "posterior_event_probabilities")
could produce out put with the same shape (row per data type) and posterior means and sds

**Comment by integrated-inferences** [comment]
PUNCHLIST 

Recap on remaining issues:

1. these need print methods
grab(model, object = "posterior_event_probabilities")
grab(model, object = "stan_objects")

2.  I think the output of `query_model` could have a print method

3. Stop exporting print methods if possible

4. Make sense of this weirdness: (summary is applied to the head rather than to the object itself) grab(model, object = "posteriors") |> head()
